
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Jun 29 21:48:04 CEST 2021
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ISGREATEREQUAL = 37;
  public static final int INCREMENT = 21;
  public static final int CONST = 26;
  public static final int NUMCONST = 29;
  public static final int HASH = 42;
  public static final int LPAREN = 27;
  public static final int SEMI = 11;
  public static final int ISLOWER = 38;
  public static final int MINUS = 3;
  public static final int DECREMENT = 22;
  public static final int RPAREN = 28;
  public static final int AND = 41;
  public static final int OR = 40;
  public static final int COMMA = 14;
  public static final int CLASS = 15;
  public static final int LEFTSQUARE = 12;
  public static final int PLUS = 2;
  public static final int IF = 32;
  public static final int EOF = 0;
  public static final int EQUAL = 20;
  public static final int NEW = 25;
  public static final int error = 1;
  public static final int ISEQUAL = 34;
  public static final int MODULO = 6;
  public static final int IDENT = 10;
  public static final int VOID = 17;
  public static final int RIGHTSQUARE = 13;
  public static final int ISNOTEQUAL = 35;
  public static final int COLON = 24;
  public static final int LBRACE = 8;
  public static final int ELSE = 33;
  public static final int READ = 18;
  public static final int CHARCONST = 30;
  public static final int ISGREATER = 36;
  public static final int RBRACE = 9;
  public static final int ISLOWEREQUAL = 39;
  public static final int BOOLCONST = 31;
  public static final int EXTENDS = 16;
  public static final int PROG = 7;
  public static final int QUESTION = 23;
  public static final int DIVISION = 5;
  public static final int MULTIPLICATION = 4;
  public static final int PRINT = 19;
}

